[package]
name = "file_system_worker"
version = "0.2.0"
authors = ["Valentin NOEL <valent.noel@gmail.com>"]

[dependencies]
amqp_worker = "0.2.2"

env_logger = "0.5.10"
futures = "^0.1"
log = "^0.4"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
tokio-core = "= 0.1.13"
