[package]
name = "clean_worker"
version = "0.1.0"
authors = ["Valentin NOEL <valent.noel@gmail.com>"]

[dependencies]
futures = "^0.1"
tokio-core = "^0.1"
lapin-futures = "^0.10"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
