[package]
name = "file_system_worker"
version = "0.2.2"
authors = [
  "Marc-Antoine ARNAUD <maarnaud@media-io.com>",
  "Valentin NOEL <valent.noel@gmail.com>"
]
edition= "2018"

[dependencies]
mcai_worker_sdk = "0.10.1"

[build-dependencies]
built = "0.4"
